# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170926_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('ranking',), 'verbose_name': 'TODO', 'verbose_name_plural': 'TODOs'},
        ),
        migrations.AlterField(
            model_name='todo',
            name='ranking',
            field=models.IntegerField(),
        ),
    ]
